baseURL: https://evekeen.github.io/speedgun.ivkin.dev
publishdir: docs
languageCode: en-us
title: Speed gun app
theme: fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:    
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Measure speed
    subtitle: In realtime, on your smartphone. Put your aces on the radar!
    buttontext: Get started
    buttonlink: "https://docs.google.com/forms/d/e/1FAIpQLSdvOMnKDZIMmCms50UHNC-tuXCdTwFudK_6v229IYzU8O5Wtg/viewform"
    image: illustrations/tennis.gif  
  section2:
    title: We're happy to introduce the best speed gun app!
    subtitle: Your game will never be the same
    features:
    - title: Instant feedback
      text: Measure the speed of your serve in realtime at a court
      # Icon (from /images/illustrations/icons/___.svg)
      icon: fast-stopwatch.png
    - title: Track your progress
      text: Keep track of the results while working on the form
      icon: chart.png
    - title: Share with friends
      text: Compete with others on social media
      icon: globe.png
  footer:
    # Logo (from /images/logos/___)
    logo: speedometer.png
    bulmalogo: false
    quicklinks:
      column1:
        title: "Author"
        links:
        - text: Alexander Ivkin
          link: https://ivkin.dev
      column2:
        title: "Other products"
        links:
        - text: Ace Trace
          link: https://acetrace.app              